<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <AssemblyName>Cratis.Applications</AssemblyName>
        <RootNamespace>Cratis.Applications</RootNamespace>
    </PropertyGroup>
    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>
    <ItemGroup>
<!-- <PackageReference Include="Cratis.Fundamentals"/> -->
  <ProjectReference Include="..\..\..\..\Fundamentals\Source\DotNET\Fundamentals\Fundamentals.csproj" />

        <PackageReference Include="FluentValidation" />
        <PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" />
        <PackageReference Include="Microsoft.Extensions.Hosting" />
        <PackageReference Include="Microsoft.Extensions.Logging" />
        <PackageReference Include="Microsoft.Extensions.Telemetry" />
    </ItemGroup>
</Project>
